# Generated by Django 6.0.2 on 2026-02-19 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('official', 'Health Official'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('public', 'Public User')], default='official', max_length=20),
        ),
        migrations.CreateModel(
            name='HITLFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirm', 'Confirmed — Real Outbreak'), ('dismiss', 'Dismissed — False Positive / Noise')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the decision')),
                ('noise_keywords', models.JSONField(default=list, help_text='Keywords identified as noise from this dismissal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.outbreakalert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoiseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hitlfeedback')),
            ],
        ),
    ]
